# Generated by Django 4.1.5 on 2023-03-02 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_subcategory_cat_product_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.category'),
        ),
    ]
