# Generated by Django 4.1.5 on 2023-03-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(choices=[('Home', 'home'), ('Office', 'Office')], max_length=20),
        ),
    ]
